apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.serviceName }}
        {{- if .Values.environment }}
        env:
          {{- range $key, $val := .Values.environment }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.memoryRequests }}
            cpu: {{ .Values.cpuRequests }}
          limits:
            memory: {{ .Values.memoryLimits }}
            cpu: {{ .Values.cpuLimits }}
        ports:
        - containerPort: {{ .Values.applicationPort }}
          name: http
        imagePullPolicy: Always