memoryRequests: "2G"
cpuRequests: "1000m"
memoryLimits: "3G"
cpuLimits: "2500m"
namespace: vsts-agents
image: microsoft/vsts-agent:ubuntu-16.04-standard
vstsAccount: hmcts
vstsPool: mgmt-aks-sandbox
vstsAgentName: rhubarb-agent 