applicationPort: 8080
environment:
configmap:
resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
resources:
  limits:
    memory: "512Mi"
    cpu: "200m"

postgres:
  enabled: false
#  image: postgres:10-alpine
#  config:
#    POSTGRES_HOST: localhost
#    POSTGRES_USER: hmcts
#    POSTGRES_PASSWORD: hmcts
#    POSTGRES_DB: hmcts
    
# Don't modify below here
namespace:
serviceName: 
image: 
ingress:
  host: 