---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceName }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}