---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.applicationPort }}
  selector:
    app: {{ .Values.serviceName }}